trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Завдання: Скопіювати файли, які нам потрібні
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      flows.json
      flows_cred.json
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Копіювання файлів Node-RED'

# Завдання: Опублікувати артефакт (файли)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Опублікувати артефакти'
