trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'odingradys/node-red-flow'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
